// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.6
// source: openweather/openweatherv1.proto

package openweather

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// OpenweatherClient is the client API for Openweather service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type OpenweatherClient interface {
	GetWeather(ctx context.Context, in *GetWeatherRequest, opts ...grpc.CallOption) (*Weather, error)
}

type openweatherClient struct {
	cc grpc.ClientConnInterface
}

func NewOpenweatherClient(cc grpc.ClientConnInterface) OpenweatherClient {
	return &openweatherClient{cc}
}

func (c *openweatherClient) GetWeather(ctx context.Context, in *GetWeatherRequest, opts ...grpc.CallOption) (*Weather, error) {
	out := new(Weather)
	err := c.cc.Invoke(ctx, "/weather.openweather.v1.Openweather/GetWeather", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OpenweatherServer is the server API for Openweather service.
// All implementations must embed UnimplementedOpenweatherServer
// for forward compatibility
type OpenweatherServer interface {
	GetWeather(context.Context, *GetWeatherRequest) (*Weather, error)
	mustEmbedUnimplementedOpenweatherServer()
}

// UnimplementedOpenweatherServer must be embedded to have forward compatible implementations.
type UnimplementedOpenweatherServer struct {
}

func (UnimplementedOpenweatherServer) GetWeather(context.Context, *GetWeatherRequest) (*Weather, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetWeather not implemented")
}
func (UnimplementedOpenweatherServer) mustEmbedUnimplementedOpenweatherServer() {}

// UnsafeOpenweatherServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OpenweatherServer will
// result in compilation errors.
type UnsafeOpenweatherServer interface {
	mustEmbedUnimplementedOpenweatherServer()
}

func RegisterOpenweatherServer(s grpc.ServiceRegistrar, srv OpenweatherServer) {
	s.RegisterService(&Openweather_ServiceDesc, srv)
}

func _Openweather_GetWeather_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetWeatherRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OpenweatherServer).GetWeather(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/weather.openweather.v1.Openweather/GetWeather",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OpenweatherServer).GetWeather(ctx, req.(*GetWeatherRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Openweather_ServiceDesc is the grpc.ServiceDesc for Openweather service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Openweather_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "weather.openweather.v1.Openweather",
	HandlerType: (*OpenweatherServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetWeather",
			Handler:    _Openweather_GetWeather_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "openweather/openweatherv1.proto",
}
