// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.6
// source: weatherstack/weatherstackv1.proto

package weatherstack

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// WeatherstackClient is the client API for Weatherstack service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WeatherstackClient interface {
	GetCurrentWeather(ctx context.Context, in *GetCurrentWeatherRequest, opts ...grpc.CallOption) (*CurrentWeather, error)
}

type weatherstackClient struct {
	cc grpc.ClientConnInterface
}

func NewWeatherstackClient(cc grpc.ClientConnInterface) WeatherstackClient {
	return &weatherstackClient{cc}
}

func (c *weatherstackClient) GetCurrentWeather(ctx context.Context, in *GetCurrentWeatherRequest, opts ...grpc.CallOption) (*CurrentWeather, error) {
	out := new(CurrentWeather)
	err := c.cc.Invoke(ctx, "/weather.weatherstack.v1.Weatherstack/GetCurrentWeather", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WeatherstackServer is the server API for Weatherstack service.
// All implementations must embed UnimplementedWeatherstackServer
// for forward compatibility
type WeatherstackServer interface {
	GetCurrentWeather(context.Context, *GetCurrentWeatherRequest) (*CurrentWeather, error)
	mustEmbedUnimplementedWeatherstackServer()
}

// UnimplementedWeatherstackServer must be embedded to have forward compatible implementations.
type UnimplementedWeatherstackServer struct {
}

func (UnimplementedWeatherstackServer) GetCurrentWeather(context.Context, *GetCurrentWeatherRequest) (*CurrentWeather, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCurrentWeather not implemented")
}
func (UnimplementedWeatherstackServer) mustEmbedUnimplementedWeatherstackServer() {}

// UnsafeWeatherstackServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WeatherstackServer will
// result in compilation errors.
type UnsafeWeatherstackServer interface {
	mustEmbedUnimplementedWeatherstackServer()
}

func RegisterWeatherstackServer(s grpc.ServiceRegistrar, srv WeatherstackServer) {
	s.RegisterService(&Weatherstack_ServiceDesc, srv)
}

func _Weatherstack_GetCurrentWeather_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCurrentWeatherRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WeatherstackServer).GetCurrentWeather(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/weather.weatherstack.v1.Weatherstack/GetCurrentWeather",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WeatherstackServer).GetCurrentWeather(ctx, req.(*GetCurrentWeatherRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Weatherstack_ServiceDesc is the grpc.ServiceDesc for Weatherstack service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Weatherstack_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "weather.weatherstack.v1.Weatherstack",
	HandlerType: (*WeatherstackServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetCurrentWeather",
			Handler:    _Weatherstack_GetCurrentWeather_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "weatherstack/weatherstackv1.proto",
}
